##LAB 1
20/08/2026
##Numpy and pandas

## 1D Numpy Arrays

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
print("the version of numpy:",np.__version__)
print("the version of pandas :",pd.__version__)

the version of numpy: 2.0.2
the version of pandas : 2.2.3

In [ ]:
marks= np.array([76,45,98,35,93])
print("Marks:",marks)
print("Type:",type(marks))

Marks: [76 45 98 35 93]
Type: <class 'numpy.ndarray'>

In [ ]:
print("Number of dimensions :",marks.ndim)
print("Shape :",marks.shape)
print("Number of elements :",marks.size)

Number of dimensions : 1
Shape : (5,)
Number of elements : 5

In [ ]:
print("the OG",marks)
print("Adding 5 :",marks+5)
print("Multping 2:",marks*2)
print("Squring :",marks**2)

the OG [76 45 98 35 93]
Adding 5 : [ 81  50 103  40  98]
Multping 2: [152  90 196  70 186]
Squring : [5776 2025 9604 1225 8649]

In [ ]:
print("Sum of all the elements :",marks.sum())
print("The mean of all the marks :",marks.mean())
print("the max marks :",marks.max())
print("the min of the marks:",marks.min())

Sum of all the elements : 347
The mean of all the marks : 69.4
the max marks : 98
the min of the marks: 35

In [ ]:
print("The first marks :",marks[0])
print("The secound marks :",marks[1])
print("The last marks :",marks[-1])

The first marks : 76
The secound marks : 45
The last marks : 93

In [ ]:
print("Index 1 to 3 : ",marks[1:4])
print("Index of first to last ",marks[::])
print("every 2nd number:",marks[::2])

Index 1 to 3 :  [45 98 35]
Index of first to last  [76 45 98 35 93]
every 2nd number: [76 98 93]

## 2D Numpy Array

In [ ]:
st_marks=np.array([[1, 2, 3],
                  [4,5 ,6],
                  [7, 8 ,9]])
print(st_marks.shape)

(3, 3)

In [ ]:
print("Mean of all :",st_marks.mean())
print("Mean column-wise:",st_marks.mean(axis=0))
print("Mean row-wise:",st_marks.mean(axis=1))

Mean of all : 5.0
Mean column-wise: [4. 5. 6.]
Mean row-wise: [2. 5. 8.]

##Pandas DataFrame
A DataFrame is a two-dimensional tabular data stucturs

In [ ]:
data ={
    "Name":["Aun","Rahul","kiran","priya"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,88]
}
df=pd.DataFrame(data)
print(df)

    Name Branch  Marks
0    Aun    CSE     85
1  Rahul   AIML     91
2  kiran    CSE     76
3  priya   AIML     88

In [ ]:
print("Shape:",df.shape)
print("\n Columns:")
print(df.columns)

Shape: (4, 3)

 Columns:
Index(['Name', 'Branch', 'Marks'], dtype='object')

In [ ]:
import pandas as pd

data = {
    "Name": ["Aun", "Rahul", "kiran", "priya", "Amit", "Neha", "Rohit",
             "Sneha", "Vikas", "Anjali", "Arjun", "Pooja", "Karan", "Meena", "Varun"],

    "Branch": ["CSE", "AIML", "CSE", "AIML", "ECE", "CSE", "AIML",
               "ECE", "CSE", "AIML", "ECE", "CSE", "AIML", "ECE", "CSE"],

    "Marks": [85, 91, 76, 88, 82, 95, 79, 87, 73, 90, 84, 78, 93, 81, 89]
}

af = pd.DataFrame(data)

print(af)

      Name Branch  Marks
0      Aun    CSE     85
1    Rahul   AIML     91
2    kiran    CSE     76
3    priya   AIML     88
4     Amit    ECE     82
5     Neha    CSE     95
6    Rohit   AIML     79
7    Sneha    ECE     87
8    Vikas    CSE     73
9   Anjali   AIML     90
10   Arjun    ECE     84
11   Pooja    CSE     78
12   Karan   AIML     93
13   Meena    ECE     81
14   Varun    CSE     89

In [ ]:
af.head()

    Name Branch  Marks
0    Aun    CSE     85
1  Rahul   AIML     91
2  kiran    CSE     76
3  priya   AIML     88
4   Amit    ECE     82

In [ ]:
af.tail()

     Name Branch  Marks
10  Arjun    ECE     84
11  Pooja    CSE     78
12  Karan   AIML     93
13  Meena    ECE     81
14  Varun    CSE     89

In [ ]:
print("Marks colums:")
print(af["Marks"])

Marks colums:
0     85
1     91
2     76
3     88
4     82
5     95
6     79
7     87
8     73
9     90
10    84
11    78
12    93
13    81
14    89
Name: Marks, dtype: int64

In [41]:
print("First row:")
print("---------------")
print(df.iloc[0])
print()
print("Secound row:")
print("---------------")
print(df.iloc[1])
print("\n First three rows")
print("---------------")
display(df.iloc[0:3])

First row:
---------------
Name      Aun
Branch    CSE
Marks      85
Name: 0, dtype: object

Secound row:
---------------
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

 First three rows
---------------

    Name Branch  Marks
0    Aun    CSE     85
1  Rahul   AIML     91
2  kiran    CSE     76

In [42]:
display(df.iloc[0:3 , 1:4])

  Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76

In [46]:
high_Score = df[df["Marks"]>90]
display(high_Score)

    Name Branch  Marks
1  Rahul   AIML     91

In [48]:
print("Students from CSE:")
display(af[af["Branch"]=="CSE"])

Students from CSE:

     Name Branch  Marks
0     Aun    CSE     85
2   kiran    CSE     76
5    Neha    CSE     95
8   Vikas    CSE     73
11  Pooja    CSE     78
14  Varun    CSE     89

In [50]:
stu=af[af["Marks"]>=80]
stu

      Name Branch  Marks
0      Aun    CSE     85
1    Rahul   AIML     91
3    priya   AIML     88
4     Amit    ECE     82
5     Neha    CSE     95
7    Sneha    ECE     87
9   Anjali   AIML     90
10   Arjun    ECE     84
12   Karan   AIML     93
13   Meena    ECE     81
14   Varun    CSE     89

##problem

In [61]:
data ={
    "Name":["Asha","Bharat","Chetan","Divya","Esha"],
    "Dept":["CSE","ISE","CSE","AIML","ISE"],
    "Marks":[73,91,94,95,68],
    "Attendance":[75,80,78,90,88]
}
sf=pd.DataFrame(data)
print(sf)

     Name  Dept  Marks  Attendance
0    Asha   CSE     73          75
1  Bharat   ISE     91          80
2  Chetan   CSE     94          78
3   Divya  AIML     95          90
4    Esha   ISE     68          88

In [62]:
display(sf["Name"],sf["Marks"])

0      Asha
1    Bharat
2    Chetan
3     Divya
4      Esha
Name: Name, dtype: object

0    73
1    91
2    94
3    95
4    68
Name: Marks, dtype: int64

In [63]:
display(sf[sf["Marks"]>80])

     Name  Dept  Marks  Attendance
1  Bharat   ISE     91          80
2  Chetan   CSE     94          78
3   Divya  AIML     95          90

In [64]:
display(sf[sf["Attendance"]>85])

    Name  Dept  Marks  Attendance
3  Divya  AIML     95          90
4   Esha   ISE     68          88

In [65]:
display(sf[1:4])

     Name  Dept  Marks  Attendance
1  Bharat   ISE     91          80
2  Chetan   CSE     94          78
3   Divya  AIML     95          90

In [68]:
sf["Marks"].mean()

np.float64(84.2)

In [69]:
sf["Marks"].max()

95

In [70]:
display(sf[sf["Dept"]== "CSE"])

     Name Dept  Marks  Attendance
0    Asha  CSE     73          75
2  Chetan  CSE     94          78

In [76]:
display(sf[(sf["Attendance"]>85) & (sf["Marks"]>80)])

    Name  Dept  Marks  Attendance
3  Divya  AIML     95          90